export const randomText: string[] = [
  "The moon forgot its shoes, so the stars had to whisper instead.",
  "Banana clocks tick louder in a parallel dimension.",
  "Never trust a llama with a compass; they always point toward soup.",
  "Clouds are just sky-sheep dreaming of puddings.",
  "Reality hiccups every time a pigeon does calculus.",
  "My socks write poetry when I sleep too deeply.",
  "The toaster said yes, but the jam declined the invitation.",
  "If fish could knit, we’d all wear seaweed hats by law.",
  "Doorknobs hold secrets from the fifth dimension.",
  "Time melts fastest in a microwave filled with jazz.",
  "The mirrors stopped reflecting last night. They’re watching now.",
  "I asked the shadows to be quiet. They laughed in my voice.",
  "There’s something humming under the floorboards, and it knows my name.",
  "She smiled without a face, and still I knew she meant me.",
  "The clocks all tick backwards when the house is asleep.",
  "I opened a drawer and found yesterday’s dream, still breathing.",
  "Don’t look behind the curtains. It doesn’t like being seen.",
  "My reflection whispered first. I only repeated it.",
  "The wallpaper peels itself back at midnight to watch me sleep.",
  "The children’s laughter stopped, but the swing keeps moving.",
];
